global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'reporter-service'
    metrics_path: /api/article/metrics 
    static_configs:
      - targets: ['reporter-service:80']